import ThemeRegistry from "config-mui/ThemeRegistry";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

type RootProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootProps): JSX.Element {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
